tests:
  resource-availability-external:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-resource-availability:main
    config:
      create-issue: true
      urls: 
        - https://brugge-ldes.geomobility.eu/observations
        - https://ldes.telraam-api.net/locations
      max-redirects: 3
      timeout: 10
      verify-ssl: true
      check-http-availability: true
      check-https-availability: true

  certificates-external:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-check-certificate:main
    config:
      urls: 
        - https://brugge-ldes.geomobility.eu/observations
        - https://ldes.telraam-api.net/locations
      timeout: 10
      certificate-expiry-days: 30

  cors-compliance-external-basic:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-cors-compliance:main
    config:
      urls: 
        - http://edan.si.edu/saam/sparql
        - http://vocab.nerc.ac.uk/sparql/sparql
        - https://linked.bodc.ac.uk/sdn/edios/sparql/sparql
        - https://sparql.ifremer.fr/csr/query

  cors-compliance-external-advanced:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-cors-compliance:main
    config:
      urls:
        - https://sparql.ifremer.fr/csr/query
        - https://sparql.ifremer.fr/sextant_seadatanet/query
      timeout: 10
      access-control-allow-origin: '*'
      access-control-allow-methods:
        - GET
        - HEAD
        - OPTIONS
      access-control-expose-headers:
        - access-control-allow-credentials
        - access-control-allow-origin
      https-redirect: true

  cors-compliance-external-prevent-masked-errors:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-cors-compliance:main
    config:
      urls: 
        - http://edan.si.edu/saam/sparql
      probe-origin: http://edan.si.edu